export const COUNTRIES: [english: string, portuguese: string][] = [
  ['World', 'Mundo'],
  ['USA', 'EUA'],
  ['India', 'Índia'],
  ['Brazil', 'Brasil'],
  ['France', 'França'],
  ['Germany', 'Alemanha'],
  ['UK', 'Reino Unido'],
  ['Russia', 'Rússia'],
  ['S. Korea', 'Coreia do Sul'],
  ['Italy', 'Itália'],
  ['Turkey', 'Turquia'],
  ['Spain', 'Espanha'],
  ['Vietnam', 'Vietnã'],
  ['Argentina', 'Argentina'],
  ['Netherlands', 'Países Baixos'],
  ['Japan', 'Japão'],
  ['Iran', 'Irã'],
  ['Colombia', 'Colômbia'],
  ['Indonesia', 'Indonésia'],
  ['Poland', 'Polônia'],
  ['Mexico', 'México'],
  ['Australia', 'Austrália'],
  ['Ukraine', 'Ucrânia'],
  ['Malaysia', 'Malásia'],
  ['Thailand', 'Tailândia'],
  ['Austria', 'Áustria'],
  ['Israel', 'Israel'],
  ['Belgium', 'Bélgica'],
  ['Czechia', 'República Tcheca'],
  ['Portugal', 'Portugal'],
  ['South Africa', 'África do Sul'],
  ['Canada', 'Canadá'],
  ['Philippines', 'Filipinas'],
  ['Switzerland', 'Suíça'],
  ['Peru', 'Peru'],
  ['Chile', 'Chile'],
  ['Greece', 'Grécia'],
  ['Denmark', 'Dinamarca'],
  ['Romania', 'Romênia'],
  ['Sweden', 'Suécia'],
  ['Iraq', 'Iraque'],
  ['Serbia', 'Sérvia'],
  ['Bangladesh', 'Bangladesh'],
  ['Hungary', 'Hungria'],
  ['Slovakia', 'Eslováquia'],
  ['Jordan', 'Jordânia'],
  ['Georgia', 'Geórgia'],
  ['Pakistan', 'Paquistão'],
  ['Ireland', 'Irlanda'],
  ['Norway', 'Noruega'],
  ['Kazakhstan', 'Cazaquistão'],
  ['Hong Kong', 'Hong Kong'],
  ['Singapore', 'Singapura'],
  ['Morocco', 'Marrocos'],
  ['Bulgaria', 'Bulgária'],
  ['Croatia', 'Croácia'],
  ['Cuba', 'Cuba'],
  ['Lebanon', 'Líbano'],
  ['Lithuania', 'Lituânia'],
  ['Tunisia', 'Tunísia'],
  ['Slovenia', 'Eslovênia'],
  ['Finland', 'Finlândia'],
  ['Nepal', 'Nepal'],
  ['Belarus', 'Bielorrússia'],
  ['Bolivia', 'Bolívia'],
  ['UAE', 'Emirados Árabes Unidos'],
  ['Uruguay', 'Uruguai'],
  ['New Zealand', 'Nova Zelândia'],
  ['Ecuador', 'Equador'],
  ['Costa Rica', 'Costa Rica'],
  ['Guatemala', 'Guatemala'],
  ['Latvia', 'Letônia'],
  ['Azerbaijan', 'Azerbaijão'],
  ['Panama', 'Panamá'],
  ['Saudi Arabia', 'Arábia Saudita'],
  ['Sri Lanka', 'Sri Lanka'],
  ['Paraguay', 'Paraguai'],
  ['Kuwait', 'Kuwait'],
  ['Myanmar', 'Mianmar'],
  ['Palestine', 'Palestina'],
  ['Dominican Republic', 'República Dominicana'],
  ['Estonia', 'Estônia'],
  ['Bahrain', 'Barém'],
  ['Venezuela', 'Venezuela'],
  ['Moldova', 'Moldávia'],
  ['Egypt', 'Egito'],
  ['Libya', 'Líbia'],
  ['Ethiopia', 'Etiópia'],
  ['Mongolia', 'Mongólia'],
  ['Cyprus', 'Chipre'],
  ['Armenia', 'Armênia'],
  ['Honduras', 'Honduras'],
  ['Oman', 'Omã'],
  ['Bosnia and Herzegovina', 'Bósnia and Herzegovina'],
  ['Réunion', 'Ilha da Reunião'],
  ['Qatar', 'Catar'],
  ['Kenya', 'Quênia'],
  ['Zambia', 'Zâmbia'],
  ['North Macedonia', 'Macedônia do Norte'],
  ['China', 'China'],
];
